# Generated by Django 4.1.2 on 2023-10-25 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listing_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='image_url',
            new_name='image',
        ),
    ]
